# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - chmod +x binaries/hugo
  - binaries/hugo -t hugo-future-imperfect
  
before_deploy: "ls -al"

deploy:
  provider: firebase
  token: ${FIREBASE_TOKEN}
  
#after_success:
#    - firebase deploy --token=${FIREBASE_TOKEN}