# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments
# Clean and don't fail
install:
  - rm -rf public || exit 0
# Build the website
script:
  - ../binaries/hugo -t hugo-future-imperfect

after_success:
    - firebase deploy --token=${FIREBASE_TOKEN}