---
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
  blog:
    default_front_matter_template: blog
upload_dir: static
public_path: "/static"
front_matter_path: "/static"
use_front_matter_path: true
file_template: ":filename:"
version: 0.38.1
